### ISSUE TITLE
How to configure maxReceivedMessageSize ?

### ISSUE THREAD

**Issue by tayfunuyar** [rfrancotechnologies/wcf-net-core#2]
Hello,
How to add maxReceivedMessageSize to service configuration?
When  I add to maxReceivedMessageSize  service give security error.

**Comment by jsolana** [comment]
Hi, could you expand  the issue including code, error so version, etc.
https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue#how-to-file-a-bug

Thanks

**Comment by tayfunuyar** [comment]
Hi
Thank you for quick response.
Exception : The maximum message size quota for incoming messages (65536) has been exceeded.

My serviceclient has a two parameter binding and endpointconfiguration. 
Service can make a  request but when data is big give exception in  the above. 
How to increase maxReceivedMessageSize  size ?
 ![image](https://user-images.githubusercontent.com/27923376/117137715-cbce2200-adb2-11eb-8cc0-500e21334f9f.png)


Thank you
